# Generated by Django 2.0.5 on 2018-10-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.FloatField(verbose_name='A Value')),
                ('b_value', models.FloatField(verbose_name='B Value')),
                ('date', models.DateField(verbose_name='Date')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sites.Site', verbose_name='value_site')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
    ]
